name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "* */24 * * *" # runs every 24 hours
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure Git Safe Directory
        run: git config --global safe.directory /home/runner/work/Nayan-Bebale/Nayan-Bebale

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_TOKEN }}  # Or use PROFILE_SUMMARY_TOKEN if needed
        with:
          USERNAME: Nayan-Bebale
          BRANCH_NAME: "main"
