name: GitHub-Profile-Summary-Cards
on:
  schedule:
    - cron: "* */24 * * *" # runs every 24 hours
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_TOKEN }}
        with:
          USERNAME: Nayan-Bebale
          BRANCH_NAME: "main"
